// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227144447_MigracaoInicialPortugues")]
    partial class MigracaoInicialPortugues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracaoDiasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracaoGlobalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimValidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioValidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("agendas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Anamnese", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitosVida")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaDoencaAtual")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaFamiliar")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaPatologicaPregressa")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentosEmUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueixaPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisaoSistemas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("anamneses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("EnviadoPorId");

                    b.ToTable("anexos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AnexoChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemetenteId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TamanhoArquivo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArquivo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("RemetenteId");

                    b.ToTable("anexos_chat", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AtestadoMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssinadoDigitalmente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssinaturaDigital")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cid")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiasAfastamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasTotais")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpressaoDigitalCertificado")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfAssinadoBase64")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjetoCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("HashDocumento");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("atestados_medicos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BloqueioAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AprovadoPorId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Status");

                    b.ToTable("bloqueios_agenda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CertificadoSalvo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosPfxCriptografados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSenha")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpressaoDigital")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEmissor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProprietario")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSujeito")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequerSenhaAoUsar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenhaCriptografada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbprint")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidoDe")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImpressaoDigital");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("certificados_salvos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CamposEspecialidadeJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EspecialidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HipoteseDiagnosticaIA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HipoteseDiagnosticaIAGeradaEm")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("HorarioFim")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkVideo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumoIA")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResumoIAGeradoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.HasIndex("Status");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AceitoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CriadoPorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EspecialidadeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("Email");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("convites", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DadosBiometricos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CircunferenciaAbdominal")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequenciaCardiaca")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequenciaRespiratoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Glicemia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Imc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<string>("PressaoArterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaturacaoOxigenio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperatura")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoGlicemia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("dados_biometricos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Especialidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CamposPersonalizadosJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("especialidades", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistoricoClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlergiasJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CirurgiasAnteriores")
                        .HasColumnType("TEXT");

                    b.Property<string>("CirurgiasAnterioresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicoesCronicas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoencasCronicasJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitosSociaisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoFamiliar")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoFamiliarJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentosEmUsoJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicamentosUsoContinuo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("TEXT");

                    b.Property<string>("VacinacoesJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("historicos_clinicos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosAntigos")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresNovos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Acao");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs_auditoria", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Lida");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PerfilPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cns")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cns");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfis_paciente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PerfilProfissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cbo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crm")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EspecialidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRegistro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Crm");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("perfis_profissional", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PreConsulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtividadeFisica")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cirurgias")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicoesCronicas")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumoAlcool")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrequenciaCardiaca")
                        .HasColumnType("TEXT");

                    b.Property<string>("InicioSintomas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntensidadeDor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medicamentos")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesAdicionais")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesHabitos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesHistorico")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesSinaisVitais")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesSintomas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<string>("PressaoArterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaturacaoOxigenio")
                        .HasColumnType("TEXT");

                    b.Property<string>("SintomasPrincipais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tabagismo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperatura")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("pre_consultas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Prescricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AssinadoDigitalmente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssinadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssinaturaDigital")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CertificadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImpressaoDigitalCertificado")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItensJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfAssinadoBase64")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjetoCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValidadeEmDias")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("HashDocumento");

                    b.HasIndex("PacienteId");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("prescricoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RegistroSoap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Avaliacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plano")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subjetivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("registros_soap", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UploadMobile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Processado")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TamanhoArquivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("ExpiraEm");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("uploads_mobile", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailPendente")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiracaoRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiracaoTokenEmailPendente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiracaoTokenResetSenha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiracaoTokenVerificacaoEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NovoEmailPendente")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpira")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenEmailPendente")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenRedefinicaoSenha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenRedefinicaoSenhaExpira")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenResetSenha")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenTrocaEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenTrocaEmailExpira")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenVerificacaoEmail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenVerificacaoEmailExpira")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefone");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.VerificacaoEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Utilizado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UtilizadoEm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("verificacoes_email", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany("Agendas")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.Anamnese", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithOne("Anamnese")
                        .HasForeignKey("Domain.Entities.Anamnese", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Domain.Entities.Anexo", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithMany("Anexos")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("EnviadoPor");
                });

            modelBuilder.Entity("Domain.Entities.AnexoChat", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithMany("AnexosChat")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Remetente")
                        .WithMany()
                        .HasForeignKey("RemetenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("EnviadoPor");

                    b.Navigation("Remetente");
                });

            modelBuilder.Entity("Domain.Entities.AtestadoMedico", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithMany("Atestados")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.BloqueioAgenda", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany("BloqueiosAgenda")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprovadoPor");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.CertificadoSalvo", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.Consulta", b =>
                {
                    b.HasOne("Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Consultas")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Paciente")
                        .WithMany("ConsultasComoPaciente")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany("ConsultasComoProfissional")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.Convite", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriadoPor");

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("Domain.Entities.DadosBiometricos", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithOne("DadosBiometricos")
                        .HasForeignKey("Domain.Entities.DadosBiometricos", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Domain.Entities.HistoricoClinico", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Domain.Entities.LogAuditoria", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsAuditoria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.PerfilPaciente", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilPaciente")
                        .HasForeignKey("Domain.Entities.PerfilPaciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.PerfilProfissional", b =>
                {
                    b.HasOne("Domain.Entities.Especialidade", "Especialidade")
                        .WithMany("Profissionais")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithOne("PerfilProfissional")
                        .HasForeignKey("Domain.Entities.PerfilProfissional", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.PreConsulta", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithOne("PreConsulta")
                        .HasForeignKey("Domain.Entities.PreConsulta", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Domain.Entities.Prescricao", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithMany("Prescricoes")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Paciente");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("Domain.Entities.RegistroSoap", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithOne("Soap")
                        .HasForeignKey("Domain.Entities.RegistroSoap", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("Domain.Entities.UploadMobile", b =>
                {
                    b.HasOne("Domain.Entities.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Consulta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.VerificacaoEmail", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Consulta", b =>
                {
                    b.Navigation("Anamnese");

                    b.Navigation("Anexos");

                    b.Navigation("AnexosChat");

                    b.Navigation("Atestados");

                    b.Navigation("DadosBiometricos");

                    b.Navigation("PreConsulta");

                    b.Navigation("Prescricoes");

                    b.Navigation("Soap");
                });

            modelBuilder.Entity("Domain.Entities.Especialidade", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Profissionais");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("BloqueiosAgenda");

                    b.Navigation("ConsultasComoPaciente");

                    b.Navigation("ConsultasComoProfissional");

                    b.Navigation("LogsAuditoria");

                    b.Navigation("Notificacoes");

                    b.Navigation("PerfilPaciente");

                    b.Navigation("PerfilProfissional");
                });
#pragma warning restore 612, 618
        }
    }
}
